In [1]:
import numpy as np

In [3]:
print(np.__doc__)


NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the built-in ``help`` function to view a function's docstring::

  >>> help(np.sort)
  ... # doctest: +SKIP

For some objects, ``np.info(obj)`` may provide additional help.  This is
particularly 

# Numpy array

In [4]:
array = np.array([2, 3, 10, 30])
array

array([ 2,  3, 10, 30])

In [5]:
array = np.array([2, 3, 10, 30, 32.032])
array

array([ 2.   ,  3.   , 10.   , 30.   , 32.032])

In [6]:
array = np.array([2, 3, 10, 30, 32.032, "hello"])
array

array(['2', '3', '10', '30', '32.032', 'hello'], dtype='<U32')

# Lista clasica din Python

In [8]:
lista = [2, 3, 10, 30, "hello"]
lista 

[2, 3, 10, 30, 'hello']

# Operatii in numpy

In [9]:
array = np.array([2, 3, 10, 30, 32.032])
array

array([ 2.   ,  3.   , 10.   , 30.   , 32.032])

In [10]:
array  + 1

array([ 3.   ,  4.   , 11.   , 31.   , 33.032])

In [13]:
array  * 2

array([ 4.   ,  6.   , 20.   , 60.   , 64.064])

In [12]:
array + array

array([ 4.   ,  6.   , 20.   , 60.   , 64.064])

In [14]:
array = np.array([2, 3, 5, 10, 20, 30])
array > 7


array([False, False, False,  True,  True,  True])

In [15]:
array < 7

array([ True,  True,  True, False, False, False])

In [16]:
lista = [2, 3, 10, 30, 32.032]
lista > 7


TypeError: '>' not supported between instances of 'list' and 'int'

In [17]:
array = np.array([2, 3, 5, 10, 20, 30])
array[array > 7]


array([10, 20, 30])