In [5]:
import sklearn
import numpy as np
import matplotlib.pyplot as plt

In [2]:
sklearn.__doc__

'Configure global settings and get information about the working environment.'

In [3]:
from sklearn.linear_model import LinearRegression

In [4]:
model = LinearRegression()
model

LinearRegression()

In [6]:
apartamente = np.array([ [30, 30_000], [35, 50_000], [42, 60_000], [60, 78_000], [65, 81_000], [70, 90_000], [73, 95_000], [80, 100_000], [100, 120_000], [110, 140_000]])
apartamente

array([[    30,  30000],
       [    35,  50000],
       [    42,  60000],
       [    60,  78000],
       [    65,  81000],
       [    70,  90000],
       [    73,  95000],
       [    80, 100000],
       [   100, 120000],
       [   110, 140000]])

In [7]:
suprafete = apartamente[:, 0]
suprafete

array([ 30,  35,  42,  60,  65,  70,  73,  80, 100, 110])

In [8]:
preturi = apartamente[:, 1]
preturi

array([ 30000,  50000,  60000,  78000,  81000,  90000,  95000, 100000,
       120000, 140000])

In [9]:
model.fit(suprafete, preturi)

ValueError: Expected 2D array, got 1D array instead:
array=[ 30  35  42  60  65  70  73  80 100 110].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [10]:
suprafete

array([ 30,  35,  42,  60,  65,  70,  73,  80, 100, 110])

In [12]:
s_2d = np.array([ [30],  [35],  [42],  [60],  [65],  [70],  [73],  [80], [100], [110]])
s_2d

array([[ 30],
       [ 35],
       [ 42],
       [ 60],
       [ 65],
       [ 70],
       [ 73],
       [ 80],
       [100],
       [110]])

In [13]:
s_2d.ndim

2

In [14]:
suprafete.ndim

1

In [16]:
s_2d = np.array([ [30, 1990],  [35, 1988],  [42, 1990],  [60, 1990],  [65, 1990],  [70, 1990],  [73, 1990],  [80, 1990], [100, 1990], [110, 1990]])
s_2d, s_2d.ndim, s_2d.size

(array([[  30, 1990],
        [  35, 1988],
        [  42, 1990],
        [  60, 1990],
        [  65, 1990],
        [  70, 1990],
        [  73, 1990],
        [  80, 1990],
        [ 100, 1990],
        [ 110, 1990]]),
 2,
 20)

In [20]:
suprafete_2d = suprafete.reshape(( -1, 1))
suprafete_2d

array([[ 30],
       [ 35],
       [ 42],
       [ 60],
       [ 65],
       [ 70],
       [ 73],
       [ 80],
       [100],
       [110]])

In [21]:
model.fit(suprafete_2d, preturi)

LinearRegression()

In [22]:
model.intercept_

np.float64(2895.9408407684386)

In [ ]:
2895.940840768424
2895.9408407684386

2895.940840768424

In [26]:
model.predict([ [50], [70] ])

array([64177.18832891, 88689.68732417])